import Footer from '@/components/footer/footer'
import './globals.css'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
		children: React.ReactNode
	}): JSX.Element {
	return (
		<html lang="en">
			<body className="flex flex-col min-h-screen bg-relive divide-y-[1px] divide-complementary">
				<main className="flex-1">{children}</main>
				<Footer />
			</body>
		</html>
	)
}
