import Footer from '@/components/footer/footer'
import './globals.css'


export const metadata = {
	title: 'Shop',
	description: 'Generated by create next app',
}

// → Interfaces

interface PageProps {
	children: React.ReactNode
	params: string
}

export default function RootLayout(props: PageProps): JSX.Element {

	return (
		<html lang="en">

			<body className="flex flex-col min-h-screen bg-white divide-y-[1px] divide-complementary container mx-auto gap-2">
				<main className="flex-1">{props.children}</main>
				<Footer />
			</body>

		</html>
	)
}
