import './globals.css'


export const metadata = {
	title: 'Shop',
	description: 'Generated by create next app',
}

// → Interfaces

interface PageProps {
	children: React.ReactNode
}


// → Custom font

import localFont from "next/font/local"

const myFont = localFont({ src: "../../public/Naula.otf", variable: "--custom-font" })




export default function RootLayout({ children }: PageProps): JSX.Element {

	return (
		<html lang="en">

			<body className={`bg-relive ${myFont.variable}`}>
				{children}
			</body>

		</html>
	)
}
